### PR TITLE
Fix breaking change

### LINKED ISSUE #200: Breakage: C projects can no longer link libdragon using LD
I updated FlappyBird to fix breakages in the latest libdragon trunk, was able to build after #199 but when I run the resulting ROM I get:

image

This means that all existing projects using C and libdragon who have not updated to n64.mk will start producing broken builds. If debug is on, there will at least be the assertion error, but there is no indication at compile-time that anything is awry.

### PR DESCRIPTION
**Pull request by anacierdem**
This fixes #200

We are using linker's `--wrap` option to provide an alternative `__do_global_ctors` function when linking with g++. It does not actually wrap the original but just provides an alternative (new version).

When that options is not provided, the function from before #195 is used to introduce minimum breakage as possible to our knowledge.

### CODE REVIEW

File: src/do_ctors.c [hunk 1]
```diff
@@ -27,8 +27,21 @@ extern func_ptr __CTOR_END__ __attribute__((section (".data")));
...
+	while (ctor_addr > ctor_sentinel) {
+		if (*ctor_addr) (*ctor_addr)();
+		ctor_addr--;
+	}
+}
+
+/**
+ * @brief Execute global constructors
+ * This version is used by the new build system via the --wrap linker
+ * flag. When that is provided, this version will be utilized instead.
```
Comment (rasky) [inline src/do_ctors.c]: I'll add explicitly: the previous version is kept for compatibility for people not using the build system but linking directly with ld.

File: src/do_ctors.c [hunk 2]
```diff
@@ -27,8 +27,21 @@ extern func_ptr __CTOR_END__ __attribute__((section (".data")));
  */
 void __do_global_ctors()
```
Comment (rasky) [inline src/do_ctors.c:34]: I'll mention here that this version is used when linking with LD

**Review by rasky — APPROVED** [review]
OK nice solution I would say. It would be great if @meeq / @sp1187 could test it and confirm it it works with their projects that were broken  by the latest change.

**Comment by rasky** [comment]
Also please change the commit message to something more descriptive like "Fix compilation with LD that was broken by previous change"

**Comment by meeq** [comment]
This fix appears to work -- I was able to link using LD and did not hit the assertion:

image

:+1:

**Comment by anacierdem** [comment]
Oops mobile UI just merged it without asking for the message @rasky 🤷🏻‍♂️
